In [138]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import mean_squared_error

In [206]:
dataset=pd.read_csv(r'D:seo_dataset170.csv')
dataset

,Website URL,SSL Certificate,Keyword in title,Keyword in Description,Keywords in phrases,Long tail-keyword,Latent Semantic indexing Keywords,Mobile Optimized,Outbound link quality,Outbound link theme,...,Syncytial Content,Site updates,Quality of Internal Link,Link of bad Neighborhood,Big brand preference,Amp version,Contact Us Page,Page Speed via Chrome,Schema markup,Ranking
0,https://www.scnsoft.com/services/web-development,3,3,3,3,3,3,3,3,3,...,3,3,3,0,3,0,3,3,3,1
1,https://www.appnovation.com/services/web-devel...,3,3,3,3,3,3,3,3,3,...,3,3,3,0,3,0,3,3,0,2
2,https://digitalmarketing.pk/digital-marketing-...,3,3,3,3,3,3,3,2,2,...,2,2,3,0,3,0,3,3,3,3
3,https://www.intellectsoft.net/services/web-dev...,3,3,3,3,3,3,3,3,2,...,3,3,3,0,3,0,3,3,3,4
4,https://www.buzzinteractive.co/web-development...,3,2,2,2,2,3,2,2,2,...,2,2,2,0,3,0,3,2,2,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
165,https://asepswebtech.com/web-development-servi...,3,2,2,2,1,2,3,1,0,...,1,1,1,2,0,0,3,2,3,166
166,https://www.w3care.com/blog/how-custom-website...,3,2,2,1,1,1,3,2,2,...,1,1,1,1,1,0,3,1,0,167
167,https://www.websoftvalley.com/web-designer-india/,3,0,0,0,1,1,3,2,2,...,1,1,1,1,1,0,3,2,2,168
168,https://tkxel.com/,3,0,0,0,0,0,0,2,2,...,1,1,1,1,1,0,3,2,1,169
169,https://symfony.com/,3,0,0,0,0,1,3,3,3,...,1,1,1,1,1,0,3,2,3,170

In [207]:
columns_to_select = [
    'SSL Certificate', 'Keyword in title', 'Keyword in Description', 
    'Keywords in phrases ', 'Long tail-keyword', 'Latent Semantic indexing Keywords', 
    'Mobile Optimized', 'Outbound link quality', 'Outbound link theme', 
    'Sitemap', 'Multimedia', 'Image optimized', 'Duplicate Content', 
    'Relevant Content', 'Page Loading Speed via HTML', 'Rel=canonical', 
    'Grammar Spelling', 'Broken URL', 'Keyword in h1 tag', 'W3C Validator', 
    'User-Friendly Layout', 'Parked Domains', 'Content Provides value and unique', 
    'Site Architecture', 'Breadcrumb navigation', 'Youtube', 'Link from Competitor', 
    'Redirect Page', 'Page Level Relevancy', 'Link from Hub Pages', 
    'Core web vitals', 'Syncytial Content', 'Site updates', 
    'Quality of Internal Link', 'Link of bad Neighborhood', 'Big brand preference', 
    'Amp version', 'Contact Us Page', 'Page Speed via Chrome', 'Schema markup'
]

X = dataset[columns_to_select]
y = dataset['Ranking']

In [208]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 170 entries, 0 to 169
Data columns (total 42 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Website URL                        170 non-null    object
 1   SSL Certificate                    170 non-null    int64
 2   Keyword in title                   170 non-null    int64
 3   Keyword in Description             170 non-null    int64
 4   Keywords in phrases                170 non-null    int64
 5   Long tail-keyword                  170 non-null    int64
 6   Latent Semantic indexing Keywords  170 non-null    int64
 7   Mobile Optimized                   170 non-null    int64
 8   Outbound link quality              170 non-null    int64
 9   Outbound link theme                170 non-null    int64
 10  Sitemap                            170 non-null    int64
 11  Multimedia                         170 non-null    int64
 12  Image optimized                    170 non-null    int64
 13  Duplicate Content                  170 non-null    int64
 14  Relevant Content                   170 non-null    int64
 15  Page Loading Speed via HTML        170 non-null    int64
 16  Rel=canonical                      170 non-null    int64
 17  Grammar Spelling                   170 non-null    int64
 18  Broken URL                         170 non-null    int64
 19  Keyword in h1 tag                  170 non-null    int64
 20  W3C Validator                      170 non-null    int64
 21  User-Friendly Layout               170 non-null    int64
 22  Parked Domains                     170 non-null    int64
 23  Content Provides value and unique  170 non-null    int64
 24  Site Architecture                  170 non-null    int64
 25  Breadcrumb navigation              170 non-null    int64
 26  Youtube                            170 non-null    int64
 27  Link from Competitor               170 non-null    int64
 28  Redirect Page                      170 non-null    int64
 29  Page Level Relevancy               170 non-null    int64
 30  Link from Hub Pages                170 non-null    int64
 31  Core web vitals                    170 non-null    int64
 32  Syncytial Content                  170 non-null    int64
 33  Site updates                       170 non-null    int64
 34  Quality of Internal Link           170 non-null    int64
 35  Link of bad Neighborhood           170 non-null    int64
 36  Big brand preference               170 non-null    int64
 37  Amp version                        170 non-null    int64
 38  Contact Us Page                    170 non-null    int64
 39  Page Speed via Chrome              170 non-null    int64
 40  Schema markup                      170 non-null    int64
 41  Ranking                            170 non-null    int64
dtypes: int64(41), object(1)
memory usage: 55.9+ KB

In [212]:
len(y)

170

In [213]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state =40)
model=RandomForestRegressor(n_estimators=40, random_state=40)
model = model.fit(X_train, y_train)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(136, 40)
(34, 40)
(136,)
(34,)

In [214]:
y_pred=model.predict(X_test)

In [215]:
print(model.score(X_train,y_train))

0.9489195816103315

In [216]:
mse=mean_squared_error(y_test, y_pred)
print(f'Mean Squared Error:{mse}')

Mean Squared Error:491.34042279411767

In [218]:
pred = model.predict(X_test)
pred

array([ 52.725,  67.025,  39.625,  45.55 ,  56.85 , 103.375, 102.85 ,
         7.5  , 116.325,  79.4  , 133.95 ,  94.15 , 122.1  , 116.   ,
        60.65 , 116.35 , 118.9  ,  24.875, 140.8  ,  44.55 , 110.55 ,
        49.375, 112.675, 132.4  , 126.375, 142.025,  17.175,  38.875,
        44.05 , 121.125,  60.9  ,  81.775, 118.625,  62.3  ])

In [219]:
#print("X shape:", X_test)
#print("y shape:", y_test)
y_train

150    151
24      25
139    140
163    164
151    152
      ...
12      13
50      51
165    166
7        8
70      71
Name: Ranking, Length: 136, dtype: int64

In [220]:
print(model.score(X_test,y_test))

0.7476155096905435

In [221]:
gbr = GradientBoostingRegressor()

gbr.fit(X_train, y_train)

y_pred = gbr.predict(X_test)


#print(classification_report(y_test, y_pred))
print(y_test, y_pred)

75      76
53      54
18      19
46      47
67      68
102    103
154    155
5        6
119    120
59      60
122    123
40      41
112    113
125    126
69      70
111    112
65      66
23      24
152    153
54      55
113    114
37      38
64      65
137    138
115    116
143    144
28      29
11      12
42      43
130    131
48      49
121    122
126    127
35      36
Name: Ranking, dtype: int64 [ 61.79563469  68.39159004  56.5123906   51.68037186  68.271992
 101.60037165 114.08349033   8.95537237 110.83938181  64.81732151
 143.39434904  79.09848066  95.78310431 137.31424826  50.63946075
 124.52923101 118.44085212  35.54698124 128.80052458  33.43817102
 110.64044536  40.08526237 107.61886102 128.95774908 136.46488996
 150.99176314   7.78548843  46.70740764  25.95953011 116.14689474
  51.53153451  98.04292107 114.26606676  59.48514697]

In [222]:
len(X_test)

34

In [225]:
model.score(X_test,y_test)

0.7476155096905435

In [226]:
dataset.describe()

,SSL Certificate,Keyword in title,Keyword in Description,Keywords in phrases,Long tail-keyword,Latent Semantic indexing Keywords,Mobile Optimized,Outbound link quality,Outbound link theme,Sitemap,...,Syncytial Content,Site updates,Quality of Internal Link,Link of bad Neighborhood,Big brand preference,Amp version,Contact Us Page,Page Speed via Chrome,Schema markup,Ranking
count,170.0,170.000000,170.000000,170.000000,170.000000,170.000000,170.000000,170.000000,170.000000,170.000000,...,170.000000,170.000000,170.000000,170.000000,170.000000,170.000000,170.000000,170.000000,170.000000,170.000000
mean,3.0,1.123529,1.041176,0.911765,1.029412,1.170588,2.794118,2.017647,1.794118,2.511765,...,1.135294,1.347059,1.435294,0.958824,1.358824,0.052941,2.947059,1.847059,1.776471,85.505882
std,0.0,0.871664,0.831025,0.848516,0.838613,0.897244,0.736994,0.638726,0.841927,1.105330,...,0.497855,0.690268,0.651753,0.525739,0.796114,0.396162,0.249538,0.661823,1.276798,49.224669
min,3.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000
25%,3.0,1.000000,0.000000,0.000000,0.000000,0.250000,3.000000,2.000000,1.000000,3.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,3.000000,2.000000,0.000000,43.250000
50%,3.0,1.000000,1.000000,1.000000,1.000000,1.000000,3.000000,2.000000,2.000000,3.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,3.000000,2.000000,2.000000,85.500000
75%,3.0,2.000000,2.000000,1.000000,1.000000,2.000000,3.000000,2.000000,2.000000,3.000000,...,1.000000,2.000000,2.000000,1.000000,2.000000,0.000000,3.000000,2.000000,3.000000,127.750000
max,3.0,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,...,3.000000,3.000000,3.000000,2.000000,3.000000,3.000000,3.000000,3.000000,3.000000,170.000000